spring:
  application:
    name: loan-api
  datasource:
    url: jdbc:h2:file:/data/loan-api
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true