INSERT INTO TARGET VALUES(1, 'NEW');
INSERT INTO TARGET VALUES(2, 'FREQUENT');
INSERT INTO TARGET VALUES(3, 'PREMIUM');

INSERT INTO USER_TABLE VALUES(1, 1);
INSERT INTO USER_TABLE VALUES(2, 2);
INSERT INTO USER_TABLE VALUES(3, 3);
INSERT INTO USER_TABLE VALUES(4, 1);
INSERT INTO USER_TABLE VALUES(5, 2);
INSERT INTO USER_TABLE VALUES(6, 3);