version: '3'
services:
  loan-api:
    container_name: loan-container
    image: loan-api
    build: loan/
    ports:
      - "8080:8080"

  debt-api:
    container_name: debt-container
    image: debt-api
    build: debt/
    ports:
      - "8085:8085"

  payment-api:
    container_name: payment-container
    image: payment-api
    build: payment/
    ports:
      - "8086:8086"

  api-config-server:
    container_name: api-config-container
    image: api-config-server
    build: api-config-server/
    ports:
      - "8888:8888"