version: '3'
services:
  loan-api:
    container_name: loan-container
    image: loan-api
    build: loan/
    depends_on:
      - api-discovery
      - api-config-server
    restart: always
    networks:
      - 'challenge-network'

  debt-api:
    container_name: debt-container
    image: debt-api
    build: debt/
    ports:
      - "8085:8085"
    networks:
      - 'challenge-network'

  payment-api:
    container_name: payment-container
    image: payment-api
    build: payment/
    ports:
      - "8086:8086"
    networks:
      - 'challenge-network'

  api-config-server:
    container_name: api-config-container
    image: api-config-server
    build: api-config-server/
    ports:
      - "8888:8888"
    networks:
      - 'challenge-network'

  api-discovery:
    container_name: api-discovery-container
    image: api-discovery
    build: api-discovery/
    ports:
      - "8761:8761"
    restart: always
    networks:
      - 'challenge-network'

networks:
  challenge-network: